### ISSUE TITLE
Server error on clicking generate

### ISSUE THREAD

**Issue by fladderen** [NiclasvanEyk/initializer-for-laravel#69] opened 2021-11-12 13:11 UTC
The settings below generate a server error; 

https://laravel.initializer.dev/?preset&vendor=fladderen&php=8.0&starter=breeze&database=mysql&flysystem-cached=flysystem-cached&cache=redis&queue=redis&cashier=mollie&uses-horizon&uses-telescope&uses-mailhog

Created with the share button. Little side note; the share button does not include the app name and needs to be manually added.

Update; When I select none in the Payment & Billing section instead of Mollie the zip is created.

**Comment by NiclasvanEyk** [comment] 2021-11-12 13:38
Thanks for reporting the issue! 

I could find a corresponding exception in Sentry: https://sentry.io/share/issue/5f85bd2b716a4d25913737c2de33602b

Seems to be an issue that could have been caught with static analysis, maybe we should actually run psalm or phpstan during CI.

**Comment by fladderen** [comment] 2021-11-12 13:44
Hi @NiclasvanEyk , sounds good. Not really an issue for now, but I thought you would like to know. 

Ran into a different issue where Laravel and Laravel Horizon were always returning errors on the composer install. I fixed them by manually changing the package versions for both Laravel and Laravel Horizon. Would you like me to create a new ticket for this?

**Comment by NiclasvanEyk** [comment] 2021-11-12 13:53
Issues are always great, as it is hard for me to test every possible combination 😅

That would be great. Sounds like the current mechanism of resolving the package versions beforehand is a bit too primitive.

**Comment by fladderen** [comment] 2021-11-12 14:09
Yeah I can imagine, especially in these types of services. I will create a new ticket :)

**Comment by NiclasvanEyk** [comment] 2021-11-14 20:57
It seems that the commit above does not completely fix this issue, but it now produces the expected error.

Strangely enough I was not able to reproduce it locally. It might have something to do with how composer is set up for the deployment, but I have no idea why this only occurs with the mollie package.

**Comment by NiclasvanEyk** [comment] 2021-11-14 22:02
38a5f697594b68e4a44ceeadecad04c820a1c887 fixed the issue

**Closed by NiclasvanEyk** 2021-11-14 22:02 UTC
Labels: bug
