### ISSUE TITLE
$ ./initialize - Error in Git Bash (MINWG64)

### ISSUE THREAD

**Issue by Andre-ADPC** [NiclasvanEyk/initializer-for-laravel#181] opened 2022-05-29 20:30 UTC
@NiclasvanEyk 
Hi Niclas,
I wanted to try your Laravel Initializer and proceeded as per the instructions. (Really like the concept btw !)
However, I'm having a problem getting the complete initialization script to continue in my Bash terminal.
I followed your instruction note at the end of the Initializer page where the project is downloaded.
Unzipped the file into the project folder on C:\Docker-Projects\adpc-laravel-project and opened the bash terminal inside the project folder.

Here is the output data from my terminal 
`
andre@Andre-Lenovo MINGW64 /c/Docker-Projects/adpc-laravel-project
$ ./initialize

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ 🚀 Initializer for Laravel
┃
┃ This script will complete the rest of the setup needed to install the
┃ chosen components into your fresh application. This might require
┃ downloading Docker containers or requiring packages via composer
┃ multiple times, so it can take a while to complete.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Press any key to continue
`
So, the script starts, and after hitting enter to continue it throws an error from the daemon about an "absolute path" required.

`Press any key to continue

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ 🚀 Install dependencies and set up Laravel Sail
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Running initial installation inside 'initializerforlaravel/sail-php-8.1:latest'
docker: Error response from daemon: the working directory 'C:/Program Files/Git/opt' is invalid, it needs to be an absolute path.
See 'docker run --help'.

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ 💥 It looks like something went wrong!
┃
┃ Feel free to open an issue on GitHub by clicking on the link below.
┃
┃ Make sure to include helpful information such as:
┃ - the error output above
┃ - the configuration chosen before downloading the archive
┃ - your local environment (operating system, etc.)
┃ - other information that seems relevant to you
┃
┃ https://github.com/NiclasvanEyk/initializer-for-laravel/issues/new
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

andre@Andre-Lenovo MINGW64 /c/Docker-Projects/adpc-laravel-project
$
`
I tried to find more information on the error:

- docker: Error response from daemon: the working directory 'C:/Program Files/Git/opt'
- Error ref: here -> [https://github.com/docker/cli/issues/2204](url)
- Second ref: here ->  [https://github.com/git-for-windows/git/issues/577#issuecomment-166118846](url)
- And here -> [https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line/34386471#34386471](url)

I went to try and find a solution, but the double-slash ".//initializer" does not work either. Please advise.
But neither of the proposals work in my case.

My Laravel Initializer [Config Link](https://laravel.initializer.dev/?preset&vendor=adpc&php=8.1&starter=breeze&database=mysql&flysystem-sftp=flysystem-sftp&cache=redis&queue=redis&mail=mailgun&broadcasting=soketi&scout=meilisearch&cashier=paddle&uses-socialite&uses-dbal&uses-horizon&uses-mailhog&uses-telescope&uses-envoy&uses-dusk&uses-pest) 

My system:
Win 10 Pro 64 - Version (Build): 21H2 (10.0.19044)
WSL2 on Ubuntu 20.04
Docker Desktop 4.8.2.0

Your guidance is appreciated.
Thanks.

**Comment by Andre-ADPC** [comment] 2022-05-30 06:46
@NiclasvanEyk 
I have made the discovery that for it to work, I needed to $wsl into the Ubuntu server running as my default.
My mistake was for assuming that I only had to run the command from the Windows bash terminal.
The installation is churning away as I'm typing this.

Thanks, the problem seems solved.

PS: I'm totally new to using Docker. It is a bit of a pain to get it up and running properly as a dev environment, then getting past firewalls by tweaking wsl.conf in /etc folder and so on. Setting up VS Code's A9 server was a blessing in disguise as you can then use  VIM or NANO edit the Linux files safely from the Windows environment. Well, so some say, time will tell if and when corruption will set in :-)

As I was getting ready to post this with the result two errors came up during the Build. 

1. One during the Pull process "laravel.test"
2. The Dusk/Chrome build process failed with rounding up the OpenSSL installation.

I think these two might have more relevance to your script. Hope you can guide me on these two.
I have the complete terminal output saved as a text file. However, I'm not sure how to get it to you. I can email it if you are willing to contact me should you need it.
Here is the shortened version of the Dusk/SSL exception:

```
Downloading ChromeDriver binaries...

   ErrorException

  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000126:SSL routines::unexpected eof while reading

  at vendor/laravel/dusk/src/Console/ChromeDriverCommand.php:217
    213▕         if ($this->option('proxy')) {
    214▕             $streamOptions['http'] = ['proxy' => $this->option('proxy'), 'request_fulluri' => true];
    215▕         }
    216▕
  ➜ 217▕         return trim(file_get_contents($this->latestVersionUrl, false, stream_context_create($streamOptions)));
    218▕     }
```

The full terminal output would only mess up your issue folder here on GH.

Best regards,
Andre

**Comment by Andre-ADPC** [comment] 2022-05-30 06:51
I am an idiot! Only noticed now I can drop the file here!

[Terminal Output Error - adpc-laravel-project.txt](https://github.com/NiclasvanEyk/initializer-for-laravel/files/8796139/Terminal.Output.Error.-.adpc-laravel-project.txt)

**Comment by NiclasvanEyk** [comment] 2022-05-30 07:01
Hi @Andre-ADPC, thanks for your kind words. 

> My mistake was for assuming that I only had to run the command from the Windows bash terminal.

Thats a good point, I think I should at some note for windows users that makes this explicit. Honestly I don't have much experience with using Docker on windows, since I am developing either on Mac or Linux directly. 

I dont have the time to look into this in more detail, maye I can help you on Wednesday. Until then I wish you the best of luck fixing the error.

**Comment by NiclasvanEyk** [comment] 2022-06-01 08:52
I cannot reproduce your errors, so I guess it is specific to windows / your specific windows setup. When I run the linked config on mac or linux it works.

I guess you could fix your last error by skipping the `dusk:install` step. Since sail already includes a pupeteer image, the download of the binaries is actually not really needed. If you open up the `initialize` script in your text editor, there should be a section like this:

```
  90   │ echo -e '┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';
  91   │ echo -e '┃ 🚀 Setup Laravel Dusk';
  92   │
  93   │ echo -e '┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━';echo '';
  94   │
  95   │ echo './vendor/bin/sail artisan dusk:install'
  96   │ ./vendor/bin/sail artisan dusk:install
  97   │ echo '';
```

the actual line numbers may vary for your script, but here you could delete the statement on line `96`.  After the initialization has succeeded, you should still be able to run your dusk tests via `sail dusk` (see [docs](https://laravel.com/docs/9.x/sail#laravel-dusk)). 

I'll close this issue for now since I was not able to reproduce it, but feel free to ask further questions or leave any feedback.

**Closed by NiclasvanEyk** 2022-06-01 08:52 UTC

**Comment by Andre-ADPC** [comment] 2022-06-14 21:15
Thank you for your reply, and my apologies for getting back to you only now. My head was buried in some other sand pile.
I'll follow your recommendations and see how things go. Docker and WSL2 are still not great buddies in my experience. I have since stopped fiddling with it after it has broken twice. 

I will keep this package on my "to-use" list though. One day I might just get that 16" M1 Pro and move house!
